### PR TITLE
Make locale and hide_http_clone_url options configurable

### PR DESCRIPTION
**Pull request by rosenfeld**
Hi Fletcher, would you mind to pull this?

### CODE REVIEW

**Comment by fnichol** [comment]
You got it, thanks! Guess I better get in there and add some documentation. Just got it going a week ago. Have you tried building with this yet?

**Comment by rosenfeld** [comment]
I've just given it a shot, thank you for your effort. I started making a recipe for Gitorious about two days ago and then I found yours and stop developing my own recipe. I started learning Chef two days ago and I was trying to set up Gitorious with Chef for helping me to learn it.

I still didn't get it working but I guess it is a matter of chef versions. The problem I'm currently having is on this line of RVM recipe:

version   gem[:version] if gem[:version]

It seems that gem[:anything] will always return some object due to Chef DSL that allows any nested level. The error message is:

```
/usr/lib/ruby/1.8/chef/shell_out.rb:232:in `invalid!': Expected process to exit 0, but it exited with 1  (Chef::Exceptions::ShellCommandFailed)
---- Begin output of rvm ruby-1.9.2-p180@global gem install bundler -q --no-rdoc --no-ri -v "" ----
STDOUT: 
STDERR: ERROR:  While executing gem ... (OptionParser::MissingArgument)
    missing argument: -v
---- End output of rvm ruby-1.9.2-p180@global gem install bundler -q --no-rdoc --no-ri -v "" ----
Ran rvm ruby-1.9.2-p180@global gem install bundler -q --no-rdoc --no-ri -v "" returned 1
```

I'll take a look on Chef documentation and will let you know when I have a fix.

Thanks!

**Comment by rosenfeld** [comment]
Actually this is very strange. I've re-run chef and it didn't complain anymore... I'm waiting the recipe to complete to see if it will work.

**Comment by fnichol** [comment]
Yeah, that's a strange one. Hopefully it went through ok for you. If not, then I can take a look in the rvm cookbook as well. I'm still iterating on that one too :)

**Comment by rosenfeld** [comment]
Yes, I could set up Gitorious yesterday but it is still not installing withoug manual operations. I'm still working on that. I had problems with the stompserver service and substituted it by ActiveMQ. On my RVM installation, the binaries are getting installed in /usr/local/bin instead of /usr/local/rvm/bin. There were other issues too regarding how Debian uses the headers of the services for finding inter-dependency. I've already pushed some changes to my forks of RVM and Gitorious recipe of yours original ones if you are curious. Also, some dependencies were depending on rake to install and I added it to global gems on RVM recipe since it is a common requirement.

You might also be interested on my gitorious clone that adds a tree view collapse/expand feature on source view:
git://gitorious.org/~rosenfeld/gitorious/rosenfeld-gitorious.git (reference "bundler")

I'm working now, so I don't know when I'll be able to continue working on the Gitorious recipe...

Best regards!

**Comment by rosenfeld** [comment]
Also, if you are willing to talk to me by instant message, you can find me on Skype (rr.rosas) or GTalk (rr.rosas@gmail.com). I'm usually available for talking at night, after 20h Brazilian Time (UTC-3) or on weekends.

**Comment by fnichol** [comment]
Ah, I'll get myself a Debian-installed vagrant box to test with. So far I've been working with Ubuntu 10.04/10.10 and openSuSE so I'd like to get at least RVM working better there. Which release of Debian are you using yourself? I'm on GTalk as well (fletcher.nichol@gmail.com) in Canada/Mountain (UTC-7) so I'll try to ping you to follow up.

**Comment by rosenfeld** [comment]
I've added you to my Gtalk. I'm using last stable Debian (squeeze - 6.0):

http://mirror.its.dal.ca/debian-cd/6.0.0/

I would suggest you to download the netinst image.

**Pull request merged**
